/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

declare module 'nativewind' {
  import type { ComponentProps } from 'react';
  import type { ViewProps, TextProps, ImageProps, TextInputProps, TouchableOpacityProps } from 'react-native';

  export type StyledComponent<T> = T & {
    className?: string;
  };

  export type StyledView = StyledComponent<ViewProps>;
  export type StyledText = StyledComponent<TextProps>;
  export type StyledImage = StyledComponent<ImageProps>;
  export type StyledTextInput = StyledComponent<TextInputProps>;
  export type StyledTouchableOpacity = StyledComponent<TouchableOpacityProps>;
}